language: node_js
node_js: "node"
before_install:
  - npm install -g bower
  - npm install -g gulp
install:
  - npm install
  - bower install
script: ""
before_deploy:
  - gulp deploy
  - rm -rf ./deploy/assets/
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "responsive-web-page"
  skip_cleanup: true
  local_dir: deploy
